version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    env_file:
      - ./database.dev.env
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - "127.0.0.1:5432:5432"
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:5.1"
    env_file:
      - ./database.dev.env
    networks:
      - backend
    ports:
      - "127.0.0.1:5050:80"
  keycloak:
    container_name: "keycloak"
    image: "jboss/keycloak:15.0.2"
    env_file:
      - ./keycloak.dev.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:8180:8080"
      - "127.0.0.1:8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db-data:
